### ISSUE TITLE
如何使用Cut_Selected_Sound.Praat

### ISSUE THREAD

**Issue by Leong1230** [feelins/Praat_Scripts#1]
您好！
我想使用Cut_Selected_Sound.Praat脚本对sound和textgrid文件同时删除选中的噪音部分，但是我运行脚本时报错（运行时选中Textgrid myfile，edit中也选中了要删除的间隔）：
![image](https://user-images.githubusercontent.com/44676836/116838535-49523080-ac01-11eb-9a2b-6fe2ba829777.png)

请问是我哪步出错了吗？是否能提供该脚本详细的操作步骤呢？
非常感谢！

**Comment by Leong1230** [comment]
此外，虽然报上述错误，但重新打开文件时sound音频文件所选部分已经被裁剪，而text文件没有被裁剪，导致两者错位。尝试多次发现，还有把音频双倍复制的bug（本来10s的音频运行完之后变成了20s）

**Comment by feelins** [comment]
能提供一下你的示例文件吗？

**Comment by Leong1230** [comment]
已发至您163邮箱

**Comment by feelins** [comment]
已经修复，请下载最新代码。不是直接运行，查看公众号里介绍。 语音处理小站。
