### ISSUE TITLE
无法使用24-tobi_auto_annotation中的module04.praat

### ISSUE THREAD

**Issue by CharlieLei** [feelins/Praat_Scripts#2]
使用data文件夹下提供的文件后依旧报如下错误

Error: The command "Set interval text:" does not return anything; not assigned to the string variable "labw$".
Script line 310 not performed or completed:
« labw$ = Set interval text: 5, w, labeltextw$ »

**Comment by feelins** [comment]
此处是代码错误，已经修改，可下载最新的代码
